spring:
  config:
    activate:
      on-profile: default
  profiles:
    include: secret

  application:
    name: MovieBooking
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/movie_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 60
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        session_factory.statement_inspector: com.cinema.moviebooking.config.QueryCountInspector
    defer-datasource-initialization: true
  cache:
    type: redis

jwt:
  access-expiration-ms: 3600000
  refresh-expiration-ms: 604800000